### ISSUE TITLE
sort error/warnings by line/column

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#477] opened 2022-10-20 15:41 UTC
Currently errors/warnings are not sorted because they are printed immediately as soon as they are found.

**Comment by fridis** [comment] 2023-05-15 09:48
I suggest to close this issue, sorting errors by the line they are found might show errors that are caused by previous errors before the actual error. 

However, there are two variants that should be fixed

- an error should not causes subsequent errors, in particular not subsequent errors before the original error is shown
- whenever possible, code should be checked for correctness in the order the code appears in the source code file

@michaellilltokiwa, do you have any examples of these two cases and create a concrete bug entry for those? Apart from these comments, I suggest to close this issue.

**Closed** 2023-05-15 14:59 UTC
Labels: enhancement, Fuzion tools
