### ISSUE TITLE
Small example shows mismatch in type parameters for auto-generated type feature

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2232] opened 2023-11-13 17:56 UTC
This example
```
a(X type) is
  b is
  c : b is
```
produces an error on a call to `a.type` that is auto generated and not part of the source code
```
 > ./build/bin/fz test_nest.fz 

/home/fridi/fuzion/clean/fuzion/test_nest.fz:3:3: error 1: Wrong number of type parameters
  c : b is
--^
Wrong number of actual type parameters in call:
Called feature: a.type
expected 2 generic arguments for 'THIS#TYPE, X'
found 1: 'a a.X'.

one error.
```

**Comment by michaellilltokiwa** [comment] 2024-10-31 12:19
duplicate of #1576

**Closed by michaellilltokiwa** 2024-10-31 12:19 UTC
Labels: bug, front end
