### ISSUE TITLE
syntax error when using `.this.type` in lambda type syntax sugar

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1518] opened 2023-05-25 06:21 UTC
```
ex is
  c (T type) is
    b (f T -> unit) unit is abstract

  a : c a is
    redef b (f a.this.type -> unit) unit is
      f a.this.type.x

    type.x a.this.type is a

  a.b (x -> say x)
```

(I'm not sure the type signatures here are entirely the same as in the context this originally came up, this happens in `lib/has_interval.fz`, `redef for_each …` when attempting to replace `H` with `has_interval.this.type`.)

the error is:
```
ex.fz:6:28: error 1: Syntax error: expected right parenthesis ')', found operator '->'
    redef b (f a.this.type -> unit) unit is
---------------------------^
While parsing: formArgs, parse stack: formArgs, formArgsOpt, routOrField, feature, stmnt, stmnts, block, implRout, routOrField, feature, stmnt, stmnts, block, implRout, implFldOrRout, routOrField, feature, stmnt, stmnts, unit


ex.fz:6:14: error 2: Wrong argument type in redefined feature
    redef b (f a.this.type -> unit) unit is
-------------^
In 'ex.a.b' that redefines 'ex.c.b' argument type is 'ex.this.type.a.this.type', argument type should be 'Unary unit ex.this.type.a' (from 'Unary unit ex.c.T').  Original argument declared at ex.fz:3:8:
    b (f T -> unit) unit is abstract
-------^
To solve this, change type of argument to 'Unary unit ex.this.type.a' at ex.fz:6:14:
    redef b (f a.this.type -> unit) unit is
-------------^

2 errors.
```

**Comment by michaellilltokiwa** [comment] 2023-05-25 07:31
The error in the parser is mitigated by adding braces:
```
ex is
  c (T type) is
    b (f T -> unit) unit is abstract

  a : c a is
    redef b (f (a.this.type) -> unit) unit is
      f a.this.type.x

    type.x a.this.type is a

  a.b (x -> say x)
```

**Comment by simonvonhackewitz** [comment] 2024-08-08 16:00
Did something change about the `.type` syntax? The code from Michael is not working for me
```
> FUZION_DISABLE_ANSI_ESCAPES=true fz /tmp/1518_ok.fz

/tmp/1518_ok.fz:3:26: error 1: Combination of 'is' and return type is not allowed.
    b (f T -> unit) unit is abstract
-------------------------^
Keyword 'is' denotes a constructor which must not have a return type.
To solve this, either replace 'is' by '=>' or remove the return type if you want to define a constructor.


/tmp/1518_ok.fz:6:23: error 2: Syntax error: expected right parenthesis ')', found operator '.'
    redef b (f (a.this.type) -> unit) unit is
----------------------^
While parsing: pTypeList, parse stack: onetype, boundType, type, formArgs, formArgsOpt, routOrField, feature, expr, exprs, block, implRout, routOrField, feature, expr, exprs, block, implRout, implFldOrRout, routOrField, feature, expr, exprs, block, unit


/tmp/1518_ok.fz:6:24: error 3: Syntax error: expected identifier name, infix/prefix/postfix operator, 'ternary ? :', 'index' or 'set' name, found keyword 'type'
    redef b (f (a.this.type) -> unit) unit is
-----------------------^
While parsing: name, parse stack: name (twice), simpletype, typeTail, onetype, boundType, type, formArgs, formArgsOpt, routOrField, feature, expr, exprs, block, implRout, routOrField, feature, expr, exprs, block, implRout, implFldOrRout, routOrField, feature, expr, exprs, block, unit

3 errors.
```

**Comment by simonvonhackewitz** [comment] 2024-08-12 11:55
Seems to be resolved by now.

`> diff --color=always --unified /tmp/1518_orig.fz /tmp/1518_new.fz`
```diff
--- /tmp/1518_orig.fz   2024-08-12 13:49:00.397691390 +0200
+++ /tmp/1518_new.fz    2024-08-12 13:45:09.569065560 +0200
@@ -1,11 +1,11 @@
 ex is
   c (T type) is
-    b (f T -> unit) unit is abstract
+    b (f T -> unit) unit => abstract
 
   a : c a is
-    redef b (f a.this.type -> unit) unit is
+    redef b (f a.this -> unit) unit =>
       f a.this.type.x
 
-    type.x a.this.type is a
+    type.x a.this => a
 
   a.b (x -> say x)
```

```
> FUZION_DISABLE_ANSI_ESCAPES=true fz /tmp/1518_new.fz

/tmp/1518_new.fz:6:14: error 1: Wrong argument type in redefined feature
    redef b (f a.this -> unit) unit =>
-------------^
In 'ex.a.b' that redefines 'ex.c.b'
argument type is       : 'Unary unit ex.this.a.this'
argument type should be: 'Unary unit ex.this.a' (from 'Unary unit ex.c.T')

Original argument declared at /tmp/1518_new.fz:3:8:
    b (f T -> unit) unit => abstract
-------^
To solve this, change type of argument to 'Unary unit ex.this.a' at /tmp/1518_new.fz:6:14:
    redef b (f a.this -> unit) unit =>
-------------^


/tmp/1518_new.fz:9:22: error 2: Could not find called feature
    type.x a.this => a
---------------------^
Feature not found: 'a' (no arguments)
Target feature: 'ex.a.type.x'
In call: 'a'

2 errors.
```

**Comment by michaellilltokiwa** [comment] 2024-08-12 13:14
@simonvonhackewitz  good, but please add regression test

**Closed** 2024-08-13 07:43 UTC
Labels: bug, parser
