### ISSUE TITLE
segfault in small recursive example

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2180] opened 2023-10-31 22:42 UTC
This: 
```
 > echo "ones => { list 1 ones }; say ones.count" | ./build/bin/fz -jvm -

error 1: java.lang.VerifyError: (class: fzC_list_i32__count, method: fzRoutine signature: (LfzI_Cons__i32__list_i32;)I) Unable to pop operand off an empty stack
	at fzC_universe.fzRoutine(Unknown Source)
	at fzC_universe.fz_run(Unknown Source)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:90)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)


*** fatal errors encountered, stopping.

```

**Comment by michaellilltokiwa** [comment] 2023-11-28 14:04
Segmentation fault in c-backend. This should fail more gracefully.

**Comment by michaellilltokiwa** [comment] 2024-02-14 11:03
VerifyError seems fixed.

**Comment by michaellilltokiwa** [comment] 2024-02-26 12:34
duplicate of #1680

**Closed by michaellilltokiwa** 2024-02-26 12:34 UTC
Labels: bug, C backend
