### ISSUE TITLE
Division by zero causes java ArithmeticException for `u32` but not `i32`

### ISSUE THREAD

**Issue by simonvonhackewitz** [tokiwa-software/fuzion#3380] opened 2024-07-15 08:42 UTC
For `u32` this causes a java exception
```
y := (u32 1) / 0  # java.lang.ArithmeticException
```
```
error 1: java.lang.ArithmeticException: / by zero
        at java.base/java.lang.Integer.divideUnsigned(Integer.java:1495)
        at dev.flang.be.jvm.runtime.Intrinsics.u32_div(Intrinsics.java:188)
        at fzC_1u32__1infix_divide.fzRoutine($MODULE/u32.fz:54)
        at fzC_universe.fzRoutine(--builtin--:38)
        at fzC_universe.fz_run(--builtin--)
        at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:104)
        at dev.flang.util.Errors.runAndExit(Errors.java:957)
        at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:116)
        at java.base/java.lang.Thread.run(Thread.java:1570)


*** fatal errors encountered, stopping.
one error.
```

For `i32` it works
```
x := 1 / 0        # precondition failure as expected
```

**Comment by michaellilltokiwa** [comment] 2024-07-17 07:18
duplicate of #3051

**Closed by michaellilltokiwa** 2024-07-17 07:18 UTC
Labels: bug, jvm backend
