### ISSUE TITLE
check-condition failure in `Clazz.findOuter` provoked by small example 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1628] opened 2023-06-21 11:00 UTC
This small example

```
o(T type) =>
s is
  o q
  q is

_ := ref : s
```
results in this crash if pre/postconditions are enable:
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz this_type_in_clazz4error1.fz 

error 1: java.lang.Error: check-condition failed: dev.flang.air.Clazz:findOuter:2235
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.air.Clazz.findOuter(Clazz.java:2235)
	at dev.flang.air.Clazz.replaceThisType(Clazz.java:693)
	at dev.flang.air.Clazz.lambda$replaceThisType$2(Clazz.java:695)
	at dev.flang.ast.AbstractType.applyToGenericsAndOuter(AbstractType.java:1416)
	at dev.flang.ast.AbstractType.applyToGenericsAndOuter(AbstractType.java:1438)
	at dev.flang.air.Clazz.replaceThisType(Clazz.java:695)
	at dev.flang.air.Clazz.lambda$replaceThisType$2(Clazz.java:695)
	at dev.flang.util.List.map(List.java:451)
	at dev.flang.air.Clazz.actualGenerics(Clazz.java:753)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:901)
	at dev.flang.air.Clazz$1.action(Clazz.java:1580)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:112)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:99)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1463)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1530)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1560)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1574)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:455)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:199)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:405)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:870)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment] 2023-06-21 11:23
duplicate of #1391

**Closed** 2023-12-18 10:23 UTC
Labels: bug, middle end
