### ISSUE TITLE
Allow loop-defined features to be qualified?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1444] opened 2023-05-15 11:35 UTC
```
To solve this, you may qualify the feature using 'ryu_test.#loop2.this.num' or 'universe.this.num'.
```

It is in fact not possible to solve this at the moment, even if you could type out `#loop2` the counter suffix to loop is not guaranteed to stay constant for multiple invocations of Fuzion. Would it be worth to have a special feature `this_loop.num` or similar?

**Comment by fridis** [comment] 2023-05-15 13:39
Please do not create out-of-contexts issues. What did you do to create this message? What code did you run?

**Comment by michaellilltokiwa** [comment] 2024-02-21 11:19
@maxteufel Can you provide some example code here that produces a similar error message?

**Comment by michaellilltokiwa** [comment] 2024-03-25 19:57
I think this should select just loops `num`. Not sure why it does not. If user wants to call `universe.num` one would have to use full qualifier.

**Comment by michaellilltokiwa** [comment] 2024-05-21 08:37
duplicate of #2347

**Closed by michaellilltokiwa** 2024-05-21 08:37 UTC
Labels: bug, front end
