### ISSUE TITLE
`Monoid` inheriting from `numeric.this.type` causes issues

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1590] opened 2023-06-13 09:25 UTC
Currently, `numeric.type.sum` inherits from `Monoid T`, where `T` is the type parameter for `numeric`. When removing the type parameter, I need this to inherit from `Monoid numeric.this.type`. This results in errors. A (relatively) small example is this:

```
test_covariance is

  # a simple, numeric type providing special elements zero and one and operations
  # lessThan, plus, minus and to_u32
  #
  num0 is

    # special values
    #
    type.zero num0.this.type is abstract
    type.one  num0.this.type is abstract

    # if num0.this less than other?
    #
    lessThan(other num0.this.type) bool is abstract

    plus (other num0.this.type) num0.this.type is plus_intrinsic other
    plus_intrinsic (other num0.this.type) num0.this.type is abstract
    minus(other num0.this.type) num0.this.type is minus_intrinsic other
    minus_intrinsic (other num0.this.type) num0.this.type is abstract

    to_u32_loop =>
      for
        x := num0.this, x.minus num0.this.type.one
        u := u32 0, u+1
      while num0.this.type.zero.lessThan x
      else
        u

    # convert this to corresponding values as an 'u32'
    #
    to_u32 u32 is
      t := num0.this.type
      if t.zero.lessThan num0.this
        (minus t.one).to_u32 + 1
      else
        0

    # create string representation consisting of type, to_u32
    # and valueString
    #
    redef as_string => "num0.this.type {to_u32} {to_u32_loop} '$valueString'"

    # string representation of this value, to be implemented by
    # children.
    #
    valueString String is abstract

    type.sum : Monoid num0.this.type is
      redef infix ∙ (a, b num0.this.type) => a.plus b
      redef e => zero


  # integer mod 2 implementation of num0
  #
  intM2(is_zero bool) : num0 is
    fixed z => intM2 true
    fixed o => intM2 false
    fixed type.zero => test_covariance.intM2 true
    fixed type.one => test_covariance.intM2 false
    fixed lessThan(other intM2) => is_zero && !other.is_zero
    fixed plus_intrinsic(other intM2) => if is_zero then other else intM2 !other.is_zero
    fixed minus_intrinsic(other intM2) => plus other
    redef valueString => if is_zero then "0 mod 2" else "1 mod 2"

  arr array intM2 := [ intM2 true, intM2 false ]
  x (T type : num0) is
    say (arr.fold T.sum)
```

error:
```
ex2.fz:68:21: error 1: Incompatible types when passing argument in a call
    say (arr.fold T.sum)
--------------------^
Actual type for argument #1 'm' does not match expected type.
In call to          : 'array.fold'
expected formal type: 'Monoid test_covariance.this.type.intM2'
actual type found   : '((test_covariance.type test_covariance.type.THIS#TYPE).num0.#type test_covariance.this.type.num0).ref sum'
assignable to       : '((test_covariance.type test_covariance.type.THIS#TYPE).num0.#type test_covariance.this.type.num0).ref sum',
                      'Any',
                      'Monoid test_covariance.this.type.num0'
for value assigned  : 'box(x.this.T.sum)'
To solve this, you could change the type of the target 'm' to '((test_covariance.type test_covariance.type.THIS#TYPE).num0.#type test_covariance.this.type.num0).ref sum' or convert the type of the assigned value to 'Monoid test_covariance.this.type.intM2'.

one error.
```

**Comment by fridis** [comment] 2023-06-13 15:35
Here is a minimal example
```
M(A type) ref is
n is
  type.s : M n.this.type is

x (T type : n) is
  m M T := T.s
```
The problem is that in `x.T.s`, for the parent, `M n.this.type`, the type that is checked in the assignability is `M n`, while it should be `M x.T`.
```
 > ./build/bin/fz ex_1590.fz

/home/fridi/fuzion/work/ex_1590.fz:6:3: error 1: Incompatible types in assignment
  m M T := T.s
--^
assignment to field : 'x.m'
expected formal type: 'M x.T'
actual type found   : '(n.#type n).ref s'
assignable to       : '(n.#type n).ref s',
                      'Any',
                      'M n'
for value assigned  : 'box(x.this.T.s)'
To solve this, you could change the type of the target 'x.m' to '(n.#type n).ref s' or convert the type of the assigned value to 'M x.T'.

one error.
```

**Closed as completed** 2023-06-19 12:25 UTC
Labels: bug, modules, front end
