### ISSUE TITLE
Overlapping values in choice reported for `void`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2104] opened 2023-10-19 11:06 UTC
This small example
```
c : choice TRUE void is
```
falsely complains about overlapping values, and it even does so twice (see #2103).
```
 > ../../bin/fz unit_like.fz

unit_like.fz:1:1: error 1: Actual type parameters to choice type must be disjoint types
c : choice TRUE void is
^
The following types have overlapping values:
'TRUE'
'void'


<built-in>: error 2: Actual type parameters to choice type must be disjoint types
The following types have overlapping values:
'TRUE'
'void'

2 errors.
```

**Comment by michaellilltokiwa** [comment] 2023-10-19 11:37
duplicate of #1884

**Closed** 2023-10-19 11:37 UTC
Labels: bug, front end
