### ISSUE TITLE
String with embedded expression results in `IndexOutOfBoundsException

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2164] opened 2023-10-30 10:21 UTC
String constant with embedded expression results in `IndexOutOfBoundsExceptions`, see this code:
```
 > echo 'say "a{42}b".dynamic_type' | ./build/bin/fz -

error 1: *** java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Call stack:
Type.as_string: $FUZION/lib/Type.fz:46:40:
  public redef as_string => "Type of '$name'"
---------------------------------------^
(((io.#type io).out.#type io.out).default_print_handler).println: $FUZION/lib/io/print_effect.fz:55:14:
    print (s.as_string + (codepoint 10))
-------------^
io.out.println: $FUZION/lib/io/print_effect.fz:36:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:29:
public say(s Any) => io.out.println s
----------------------------^
universe#0: -:1:1:
say "a{42}b".dynamic_type
^^^



error 2: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.typeName(Clazz.java:2110)
	at dev.flang.be.interpreter.Intrinsics.lambda$static$3(Intrinsics.java:246)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:682)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:677)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:341)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:961)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$5(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:677)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:682)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:341)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:961)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$5(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:677)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:677)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:341)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:961)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$5(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:341)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:961)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$5(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:330)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:396)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:961)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$4(Interpreter.java:833)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:226)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:97)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.

```
For jvm and C backends, this fails already during DFA:
```
> echo 'say "a{42}b".dynamic_type' | ./build/bin/fz -jvm -

error 1: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.air.Clazz.typeName(Clazz.java:2110)
	at dev.flang.fuir.FUIR.clazzTypeName(FUIR.java:523)
	at dev.flang.fuir.analysis.dfa.DFA.lambda$static$2(DFA.java:1233)
	at dev.flang.fuir.analysis.dfa.Call.result(Call.java:208)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:392)
```

**Comment by michaellilltokiwa** [comment] 2023-11-23 11:00
this fails as well: `echo 'say 1.as_string.dynamic_type' | fz -`

**Comment by michaellilltokiwa** [comment] 2024-03-20 07:27
duplicate of #2402

**Closed by michaellilltokiwa** 2024-03-20 07:27 UTC
Labels: bug, optimizer/analyzer, C backend, interpreter backend, jvm backend
