### ISSUE TITLE
AoC issue: ArithmeticException in Fuzion working with array consts

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2372] opened 2023-12-14 17:15 UTC
This code
```
    area := array2 String 1 1 i,j->""
    for s Sequence (array2 String) := [], s ++ []
        ss Sequence String := [], ss ++ [$a]
        a := area, a #|> tilt |> left |> tilt |> left |> tilt |> left |> tilt |> left
    do
```
results in
```
 > /home/fridi/fuzion/clean/fuzion/build//bin/fz part2_arithemtic_exception2.fz 

error 1: java.lang.ArithmeticException: / by zero
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.newArrayConst(DFA.java:588)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.constData(DFA.java:507)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:680)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1178)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2054)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2016)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1081)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:940)
	at dev.flang.be.jvm.JVM.<init>(JVM.java:762)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.
```

**Comment by michaellilltokiwa** [comment] 2023-12-15 08:16
fixed by #2240. 

The problem is that this returns true for empty string arrays but backend support for const string arrays is only implemented in #2240:
```
  private boolean isConst(InlineArray ia)
  {
    return
      !ia.type().dependsOnGenerics() &&
      !ia.type().containsThisType() &&
      // some backends have special handling for array void.
      ia.elementType().compareTo(Types.resolved.t_void) != 0 &&
      ia._elements
        .stream()
        .allMatch(el -> {
          var s = new List<>();
          super.toStack(s, el);
          return s
            .stream()
            .allMatch(x -> isConst(x));
        });
  }
```

**Closed** 2023-12-18 10:10 UTC
Labels: bug, middle end
