### ISSUE TITLE
"Type not found" for feature defined in type feature

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1491] opened 2023-05-23 07:11 UTC
```
ex is
  type.a_type_feature is
    feature_defined_in_type_feature is
    a option feature_defined_in_type_feature is
```

```
sam@debian ~/n/fuzion (transducer_type_feature)$ fz ~/playground/test.fz 

/home/sam/playground/test.fz:4:14: error 1: Type not found
    a option feature_defined_in_type_feature is
-------------^
Type 'feature_defined_in_type_feature' was not found, no corresponding feature nor formal type parameter exists
Type that was not found: 'feature_defined_in_type_feature'
in feature: 'ex.type.a_type_feature.a'
However, one feature has been found that matches the type name but that does not define a type:
'ex.type.a_type_feature.feature_defined_in_type_feature' defined at /home/sam/playground/test.fz:3:5:
    feature_defined_in_type_feature is
----^

To solve this, check the spelling of the type you have used.

one error.
```

**Comment by fridis** [comment] 2023-05-24 06:39
This is not a bug, but an enhancement request. From the visibility point of view, type features live in a completely different scope than the corresponding original features. The reason is that in your example, there is no surrounding instance of `ex`, so features declared within `ex` cannot be called in the type feature. 
However, we could relax this and make types visible, such that your example works. Need to think about what to do in case the surrounding feature `ex` has type parameters, would this still work? Probably yes, need to check.

**Comment by fridis** [comment] 2023-05-24 07:49
I did not look at the example well enough, this is really a bug. Currently there seems to be no way to access that type, also the syntax `ex.type.a_type_feature.feature_defined_in_type_feature` does not work. 
This should be fixed. 
Nevertheless, I think it might be better style to declared types outside of type features.

**Closed** 2024-05-14 09:48 UTC
Labels: bug, front end
