### ISSUE TITLE
Error `Could not find called feature` causes `java.lang.IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by simonvonhackewitz** [tokiwa-software/fuzion#3348] opened 2024-07-09 14:46 UTC
This is the code
```
out :=
  for res list i32 := nil, res ++ new_res
      i := 0, i+1
  while i<10
  do
    new_res := [i]
  else
    res.take res.count - 3 # parentheses missing or spaces around minus wrong
say out
```

And the error message is
```
/home/simon/playground/java_exception_test.fz:8:24: error 1: Could not find called feature
    res.take res.count - 3 # parentheses missing
-----------------------^
Feature not found: 'infix -' (one argument)
Target feature: 'list'
In call: 'res.take res.count - 3'


error 2: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:365)
        at java.base/java.util.ArrayList.get(ArrayList.java:428)
        at dev.flang.fe.SourceModule.inScope(SourceModule.java:1325)
        at dev.flang.fe.SourceModule.lookup0(SourceModule.java:1233)
        at dev.flang.fe.SourceModule.lookup(SourceModule.java:1138)
        at dev.flang.ast.Call.findOnTarget(Call.java:763)
        at dev.flang.ast.Call.loadCalledFeatureUnlessTargetVoid(Call.java:670)
        at dev.flang.ast.Call.resolveTypes(Call.java:2265)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1375)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1366)
        at dev.flang.ast.Call.visit(Call.java:1149)
        at dev.flang.ast.Call.visit(Call.java:1146)
        at dev.flang.ast.Resolution.resolveType(Resolution.java:562)
        at dev.flang.ast.Call.lambda$resolveTypesOfActuals$9(Call.java:934)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1437)
        at dev.flang.ast.Resolution.resolveTypes(Resolution.java:543)
        at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:2397)
        at dev.flang.ast.Call.resolveTypes(Call.java:2308)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1375)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1366)
        at dev.flang.ast.Call.visit(Call.java:1149)
        at dev.flang.ast.Block.visit(Block.java:211)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visitExpr(Impl.java:324)
        at dev.flang.ast.Feature.visit(Feature.java:2011)
        at dev.flang.ast.Block.visit(Block.java:211)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:300)
        at dev.flang.ast.Feature.visit(Feature.java:1117)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1426)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:442)
        at dev.flang.ast.Resolution.resolve(Resolution.java:409)
        at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:269)
        at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:195)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:1068)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:141)
        at dev.flang.util.Errors.runAndExit(Errors.java:957)
        at dev.flang.tools.Tool.run(Tool.java:141)
        at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.
2 errors.
```

**Comment by michaellilltokiwa** [comment] 2024-07-10 10:06
I'm failing to reproduce this issue:
```
/home/not_synced/fuzion (2024-07-10T11-49-42+02-00)1$ cat ~/playground/test.fz
out :=
  for res list i32 := nil, res ++ new_res
      i := 0, i+1
  while i<10
  do
    new_res := [i]
  else
    res.take res.count - 3 # parentheses missing or spaces around minus wrong
say out
/home/not_synced/fuzion (2024-07-10T11-49-42+02-00)$ make base-only && fz ~/playground/test.fz 

/home/sam/playground/test.fz:8:24: error 1: Could not find called feature
    res.take res.count - 3 # parentheses missing or spaces around minus wrong
-----------------------^
Feature not found: 'infix -' (one argument)
Target feature: 'list'
In call: 'res.take res.count - 3'

one error.
/home/not_synced/fuzion (2024-07-10T11-49-42+02-00)1$ 
```

**Comment by michaellilltokiwa** [comment] 2024-07-10 10:33
Can reproduce going back to before #3322 was merged. Closing since code relevant code was changed.

**Closed by michaellilltokiwa** 2024-07-10 10:33 UTC
Labels: bug, front end
