### ISSUE TITLE
parser fails to parse `this.type` in lambda type syntax sugar

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1633] opened 2023-06-22 07:20 UTC
```
ex is
  foo (f ex.this.type -> unit) unit is unit
```
does not work:
```
ex.fz:2:37: error 1: Syntax error: expected semicolon ';', found keyword 'is'
  foo (f ex.this.type -> unit) unit is unit
------------------------------------^
While parsing: semicolon or flat line break, parse stack: semiOrFlatLF, stmnts, block, implRout, implFldOrRout, routOrField, feature, stmnt, stmnts, unit


ex.fz:2:3: error 2: Could not find called feature
  foo (f ex.this.type -> unit) unit is unit
--^
Feature not found: 'foo' (2 arguments)
Target feature: 'ex'
In call: 
foo ({
  f dev.flang.ast.DotType@61e717c2.infix -> unit
}) unit


2 errors.
```
but
```
ex is
  foo (f Unary unit ex.this.type) unit is unit
```
does. It should be possible to use the first variant. (See also `lib/has_interval.fz` where I had to change this in the `numeric` pull request).

**Comment by michaellilltokiwa** [comment] 2024-03-04 11:18
duplicate of #1518

**Closed by michaellilltokiwa** 2024-03-04 11:18 UTC
Labels: bug, parser
