### ISSUE TITLE
AoC: Lambda result type inference produces error

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#4478] opened 2024-12-11 11:14 UTC
Ran into this during [Dec 11 Advent of Code](https://github.com/fridis/fuzion_aoc/blob/main/2024/11/part1.fz) this example that works fine when giving the type parameter `bool` for the call to `flat_map B f`
```
 > ./build/bin/fz -e 'say ([1,2,3].flat_map bool _->[true,false])'[true, false, true, false, true, false]
```
the type inference manages to infer `bool` for `B`here, so we should be able to omit it, but then we run into another error:
```
 > ./build/bin/fz -e 'say ([1,2,3].flat_map _->[true,false])'

command line:1:23: error 1: Incompatible types when passing argument in a call
say ([1,2,3].flat_map _->[true,false])

Actual type for argument #1 'f' does not match expected type.
In call to          : 'Sequence.flat_map'
expected formal type: 'Unary (Sequence bool) i32'
actual type found   : 'universe.this.λ'
assignable to       : 'Any',
                      'Function (array bool) i32',
                      'Unary (array bool) i32',
                      'universe.this.λ'
for value assigned  : '_->[true,false]'
To solve this, you could change the type of the target 'f' to 'universe.this.λ' or convert the type of the assigned value to 'Unary (Sequence bool) i32'.

one error.
```
Problem is that during type inference, the result type of the lambda is fixed to `array bool`, while this should not happen since the result type is defined by `flat_map` to be `Sequence B`.

**Comment by michaellilltokiwa** [comment] 2024-12-11 15:30
duplicate of #1355

**Closed as completed by michaellilltokiwa** 2024-12-11 15:30 UTC
Labels: bug, front end
